### ISSUE TITLE
Errors in Includes

### ISSUE THREAD

**Issue by crnorris** [adafruit/Adafruit_10DOF#1]
The include `<Math.h>` should be `<math.h>` as this causes a problem on Unix-like systems. It appears that the import `<Adafruit_L3GD20_U.h>` is missing also.

**Comment by drmes** [comment]
Ditto!

**Comment by microbuilder** [comment]
Fixed, thanks for the heads up.

**Comment by drmes** [comment]
The file, Adafruit_L3GD20_U.h, should be included in pitchrollheading.pde also.
